---
title: "Palmer Penguins Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: ["twitter","facebook","linkedin"]
    source_code: embed
    theme:
      version: 4
      bootswatch: lumen
---

```{r setup, include=FALSE}
# Load packages
library(flexdashboard)
library(tidyverse)
library(palmerpenguins)
library(plotly)
library(DT)
library(fontawesome)
library(ggridges)
library(ggdist)

# Load data
penguins <- palmerpenguins::penguins

```

Plots {data-navmenu="Pages"}
=======================================================================

<!--sidebar {.sidebar}
-----------------------------------------------------------------------

### Penguin Stats

The number of penguins in the data is `r nrow(penguins)`

!-->

Row
-----------------------------------------------------------------------

### Number of Penguins

```{r}

valueBox(nrow(penguins), icon = "fa-linux")

```


Column {.tabset}
-----------------------------------------------------------------------

### Scatter Plot of Bill Length vs Bill Depth

```{r}

peng_scatter <- penguins %>% 
  na.omit() %>% 
  ggplot(aes(bill_length_mm, bill_depth_mm, color = species)) +
  geom_jitter() +
  scale_color_viridis_d(option = "turbo") +
  theme_minimal() +
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       color = "Penguin Species")

ggplotly(peng_scatter)

```



### Raincloud Plot of Penguin Body Mass by Sex

```{r}

penguins %>%
  mutate(sex = str_to_title(sex)) %>% 
  na.omit() %>% 
  ggplot(aes(body_mass_g, sex, fill = sex, color = sex)) +
  geom_density_ridges(jittered_points = TRUE, position = "raincloud", alpha = 0.5) +
  scale_fill_manual(values = c("dodgerblue1","orange1")) +
  scale_color_manual(values = c("dodgerblue1","orange1")) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = "Penguin Body Mass (g)",
       y = "")
```

### Dotplot of Distribution of Flipper Length by Species

```{r}

penguins %>% 
  na.omit() %>% 
  ggplot(aes(flipper_length_mm, fill = species, color = species)) +
  geom_dots() +
  scale_color_viridis_d(option = "turbo") +
  scale_fill_viridis_d(option = "turbo") +
  facet_wrap(~species) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = "Flipper Length (mm)")

```

Data {data-navmenu="Pages"}
=====================================================

```{r}

penguins %>% 
  datatable(extensions = "Buttons",
            options = list(dom = "Blfrtip",
                           buttons = c("copy","csv","excel","pdf","print")))

```

